name: message_app
description: chat application created with parse server
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#API
  parse_server_sdk_flutter: ^3.1.0
  flutter_dotenv: ^5.0.2

#State Management & Utils
  get: ^4.6.1
  get_storage: ^2.0.3

#Fonts & Icons
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  flutter_feather_icons: ^2.0.0+1
  font_awesome_flutter:
  flutter_shapes:

#Widgets  
  tcard: ^1.3.5
  fl_chart: ^0.36.3
  flutter_slidable: ^0.6.0
  glassmorphism: ^2.0.1  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/memoji/
    - assets/icon/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

